version: "3"

# Must have BuildKit enabled
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

services:
  redsocks:
    image: redsocks
    restart: unless-stopped
    network_mode: host
    privileged: true
    build:
      context: redsocks
      dockerfile: Dockerfile
      network: host
    entrypoint: "/usr/local/bin/redsocks.sh 127.0.0.1 7777"
  socks-over-https:
    network_mode: host
    image: socks-over-https
    restart: unless-stopped
    environment:
      - SOCKS_IP=$SOCKS_IP
      - SOCKS_PORT=$SOCKS_PORT
      - HTTPS_IP=$HTTPS_IP
      - HTTPS_PORT=$HTTPS_PORT
      - PROXY_USER=$PROXY_USER
      - PROXY_PASS=$PROXY_PASS
    build:
      context: socks-over-https
      dockerfile: Dockerfile
      network: host
