version: "2"

# Must have BuildKit enabled
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

services:
  proxy:
    network_mode: host
    image: 
  app:
    depends_on:
      - socks
    restart: always
    image: ubuntu:latest
    
