version: "3"

# Must have BuildKit enabled
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

services:
  rs2:
    image: redsocks2
    restart: unless-stopped
    network_mode: host
    cap_add:
      - NET_ADMIN
    build:
      context: redsocks2
      dockerfile: Dockerfile
      network: host
  soh:
    network_mode: host
    image: socks-over-https
    restart: unless-stopped
    environment:
      - SOCKS_IP=$SOCKS_IP
      - SOCKS_PORT=$SOCKS_PORT
      - HTTPS_IP=$HTTPS_IP
      - HTTPS_PORT=$HTTPS_PORT
      - PROXY_USER=$PROXY_USER
      - PROXY_PASS=$PROXY_PASS
    build:
      context: socks-over-https
      dockerfile: Dockerfile
      network: host
