version: "3"

# Must have BuildKit enabled
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

services:
  redsocks:
    image: redsocks
    restart: unless-stopped
    network_mode: host
    privileged: true
    build:
      context: redsocks
      dockerfile: Dockerfile
    entrypoint: "/usr/local/bin/redsocks.sh 127.0.0.1 7777"
  socksifier:
    image: socksifier
    restart: unless-stopped
    network_mode: host
    privileged: true
    build:
      context: socks-over-https
      dockerfile: Dockerfile
      
