version: "2"

# Must have BuildKit enabled
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

networks:
  internet:
  intranet:
    internal: true

services:

  i2p:
    image: 
    
    
  firewall:
    restart: always
    # This capibility is needed to add firewall rules.
    cap_add:
      - net_admin
    # Some environment variables to configure the firewall. See the Dockerfile
    # for more about these options.
    environment:
      ALLOW_IP_ADDRESS: $PROXY_IP
      ALLOW_PORT: $PROXY_PORT
      ALLOW_PROTO: tcp

      # This is the port which a tcp socket will be opened on once the firewall
      # is ready. Containers which require the firewall to be available before
      # doing something should wait until this port is open. See below for an
      # example of how to wait.
      FIREWALL_READY_SIGNAL_PORT: 60000
    network_mode: service:vpn
    image: docker-firewall
    build:
      context: docker-firewall
      dockerfile: Dockerfile
      
  socks:
    depends_on:
      - firewall
      - i2p
    restart: always
    network_mode: service:firewall
    image: socks-over-https
    build:
      context: socks-over-https
      dockerfile: Dockerfile
  
  app:
    depends_on:
      - socks
    restart: always
    network_mode: service:socks
    image: ubuntu:latest
    
