version: "3"

# Must have BuildKit enabled
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

services:
  redsocks:
    image: redsocks
    restart: unless-stopped
    network_mode: host
    privileged: true
    build:
      context: redsocks
      dockerfile: Dockerfile
      network: host
  redudp:
    depends_on:
      - redsocks
    image: redudp
    restart: unless-stopped
    network_mode: host
    privileged: true
    build:
      context: redudp
      dockerfile: Dockerfile
      network: host
  soh:
    depends_on:
      - redsocks
      - redudp
    network_mode: host
    image: socks-over-https
    restart: unless-stopped
    environment:
      - SOCKS_IP=$SOCKS_IP
      - SOCKS_PORT=$SOCKS_PORT
      - HTTPS_IP=$HTTPS_IP
      - HTTPS_PORT=$HTTPS_PORT
      - PROXY_USER=$PROXY_USER
      - PROXY_PASS=$PROXY_PASS
    build:
      context: socks-over-https
      dockerfile: Dockerfile
      network: host
