version: "2"

# Must have BuildKit enabled
# COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build

services:
  socks:
    network_mode: host
    # restart: unless-stopped
    image: socks-over-https
    environment:
      - HTTPS_IP=$HTTPS_IP
      - HTTPS_PORT=$HTTPS_PORT
      - PROXY_USER=$PROXY_USER
      - PROXY_PASS=$PROXY_PASS
    build:
      context: socks-over-https
      dockerfile: Dockerfile
  app:
    network_mode: host
    # restart: unless-stopped
    image: ubuntu:latest
    
